# Generated by Django 2.1.7 on 2019-03-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('strava_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='strava ID')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='distance (m)')),
                ('average_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='average speed (m/s)')),
                ('start', models.DateTimeField(verbose_name='start')),
                ('moving_time', models.DurationField(blank=True, null=True, verbose_name='moving time')),
                ('elapsed_time', models.DurationField(verbose_name='elapsed time')),
                ('elevation_gain', models.IntegerField(blank=True, null=True, verbose_name='elevation gain')),
                ('sport', models.PositiveSmallIntegerField(choices=[(1, 'RUN'), (2, 'RIDE'), (3, 'HIKE'), (4, 'XC_SKI'), (5, 'ROLLER_SKI'), (6, 'ALPINE_SKI'), (7, 'SWIM'), (8, 'WALK'), (9, 'CANOENING'), (10, 'CLIMBING'), (11, 'ICE_SKATE'), (12, 'WORKOUT'), (13, 'OTHER')], verbose_name='sport')),
                ('kudos', models.IntegerField(blank=True, null=True, verbose_name='kudos count')),
                ('achievements', models.IntegerField(blank=True, null=True, verbose_name='achievements count')),
                ('comments', models.IntegerField(blank=True, null=True, verbose_name='comments count')),
                ('race', models.BooleanField(default=False, verbose_name='is race')),
                ('commute', models.BooleanField(default=False, verbose_name='is commute')),
                ('athlete_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='athlete count')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'SHOE'), (2, 'BIKE'), (3, 'SKI'), (4, 'OTHER')], verbose_name='gear type')),
                ('strava_id', models.CharField(blank=True, max_length=10, null=True, verbose_name='strava ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=30, verbose_name='slug')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='athletes',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.Athlete', verbose_name='athletes'),
        ),
        migrations.AddField(
            model_name='activity',
            name='gear',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.Gear', verbose_name='gear'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='activities', to='activities.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='accessories', to='activities.Activity', verbose_name='activities'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='gear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='activities.Gear', verbose_name='gear'),
        ),
    ]
