# Generated by Django 3.0 on 2019-12-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20191210_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='athlete_id',
            field=models.PositiveIntegerField(default=6850102, verbose_name='athlete ID'),
            preserve_default=False,
        ),
    ]
