# Generated by Django 3.0 on 2019-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_athlete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='strava_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='strava ID'),
        ),
    ]
