# Generated by Django 3.0 on 2019-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20191211_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_temp',
            field=models.IntegerField(blank=True, null=True, verbose_name='average temp'),
        ),
    ]
