# Generated by Django 3.1.1 on 2020-09-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20200928_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type_strava',
            field=models.CharField(blank=True, max_length=100, verbose_name='type Strava'),
        ),
    ]
