# Generated by Django 3.1.1 on 2020-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_type_strava'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='average_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='average power'),
        ),
        migrations.AddField(
            model_name='activity',
            name='has_power_meter',
            field=models.BooleanField(default=False, verbose_name='has power meter'),
        ),
        migrations.AddField(
            model_name='activity',
            name='kcal',
            field=models.IntegerField(blank=True, null=True, verbose_name='kCal'),
        ),
        migrations.AddField(
            model_name='activity',
            name='max_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='max power'),
        ),
        migrations.AddField(
            model_name='activity',
            name='private',
            field=models.BooleanField(default=False, verbose_name='private'),
        ),
        migrations.AddField(
            model_name='activity',
            name='suffer_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='suffer score'),
        ),
        migrations.AddField(
            model_name='activity',
            name='weighted_average_power',
            field=models.IntegerField(blank=True, null=True, verbose_name='weighted average power'),
        ),
    ]
