# Generated by Django 3.1.1 on 2022-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20220210_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='punctures_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='punctures count'),
        ),
    ]
