# Generated by Django 3.1.1 on 2023-05-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20230519_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='retired'),
        ),
        migrations.AddField(
            model_name='gear',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='retired at'),
        ),
    ]
